"""
disruption_simulator.py

Simulates dynamic shop-floor disruptions for the workstation scheduling system.
This module introduces stochastic factory-floor variations to model realistic conditions.
In an actual manufacturing shop-floor:
    1. Workstation efficiency fluctuates due to tool wear, thermal drift, or operator fatigue.
    2. Workstations experience unexpected breakdowns resulting in unplanned downtime.

The simulator tracks these live states and provides a snapshot of the actual workstation conditions
for the sequencing engine to optimize against.
"""

import random
import copy

class DisruptionSimulator:
    """
    Wraps a scheduling scenario and simulates time-varying machine conditions.
    """

    def __init__(self, scenario, seed: int = None,
                 efficiency_std: float = 0.15,
                 breakdown_prob: float = 0.05,
                 breakdown_duration_range=(10, 30)):
        """
        Args:
            scenario: dict generated by job_generator.
            seed: RNG seed for reproducibility.
            efficiency_std: standard deviation of machine efficiency shock.
            breakdown_prob: probability of a machine breaking down during a simulation step.
            breakdown_duration_range: range of ticks a breakdown lasts.
        """
        self.scenario = scenario
        self.rng = random.Random(seed)
        self.efficiency_std = efficiency_std
        self.breakdown_prob = breakdown_prob
        self.breakdown_duration_range = breakdown_duration_range

        self.time = 0
        self.machines = scenario['machines']
        
        # active_breakdowns: {machine_id: repair_ticks_left}
        self.active_breakdowns = {}
        # efficiency_multipliers: {machine_id: multiplier} (1.0 = normal, higher = slower processing)
        self.efficiency_multipliers = {m: 1.0 for m in self.machines}
        # breakdown_history: list of (machine_id, start_time, duration)
        self.breakdown_history = []

    def step(self):
        """Advance the simulated shop clock by one tick, updating machine states."""
        self.time += 1

        # 1. Update efficiency multipliers with a mean-reverting random walk
        # Slower machine = higher multiplier (takes longer to process)
        for m in self.efficiency_multipliers:
            current = self.efficiency_multipliers[m]
            shock = self.rng.gauss(0, self.efficiency_std)
            new_val = 0.8 * current + 0.2 * 1.0 + shock
            # Clamp multiplier between 0.7x (extra efficient) and 2.5x (very sluggish)
            self.efficiency_multipliers[m] = max(0.7, min(new_val, 2.5))

        # 2. Decrement active breakdowns
        repaired = []
        for m, ticks_left in self.active_breakdowns.items():
            self.active_breakdowns[m] = ticks_left - 1
            if self.active_breakdowns[m] <= 0:
                repaired.append(m)
        for m in repaired:
            del self.active_breakdowns[m]

        # 3. Trigger new breakdowns
        for m in self.machines:
            if m in self.active_breakdowns:
                continue
            if self.rng.random() < self.breakdown_prob:
                duration = self.rng.randint(*self.breakdown_duration_range)
                self.active_breakdowns[m] = duration
                self.breakdown_history.append((m, self.time, duration))

    def get_live_efficiency(self, machine_id):
        """Get the current efficiency multiplier for a machine."""
        if machine_id in self.active_breakdowns:
            return float('inf')  # Machine is offline
        return self.efficiency_multipliers.get(machine_id, 1.0)

    def get_live_scenario(self):
        """
        Produce a snapshot of the scheduling problem with adjusted processing times
        and active breakdown constraints.
        """
        live_scenario = copy.deepcopy(self.scenario)
        
        # Adjust processing times based on live efficiency multipliers
        for job_id, job in live_scenario['jobs'].items():
            for op in job['operations']:
                updated_eligible = {}
                for m, base_time in op['eligible_machines'].items():
                    mult = self.get_live_efficiency(m)
                    if mult == float('inf'):
                        updated_eligible[m] = base_time
                    else:
                        updated_eligible[m] = round(base_time * mult, 1)
                op['eligible_machines'] = updated_eligible

        # Record active breakdowns for constraints
        live_scenario['active_breakdowns'] = copy.deepcopy(self.active_breakdowns)
        live_scenario['breakdown_history'] = list(self.breakdown_history)
        
        return live_scenario

    def reset(self):
        """Reset the simulator to initial shop conditions."""
        self.time = 0
        self.active_breakdowns = {}
        self.efficiency_multipliers = {m: 1.0 for m in self.machines}
        self.breakdown_history = []

if __name__ == "__main__":
    from job_generator import generate_scheduling_problem
    
    scenario = generate_scheduling_problem(num_jobs=3, num_machines=3, seed=42)
    sim = DisruptionSimulator(scenario, seed=1)
    
    print("Initial Job 0 Ops:", scenario['jobs'][0]['operations'])
    for t in range(5):
        sim.step()
        
    live = sim.get_live_scenario()
    print("Live Job 0 Ops after 5 ticks:", live['jobs'][0]['operations'])
    print("Breakdown history:", live['breakdown_history'])
